# Generated by Django 2.2.2 on 2019-12-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalinfo', '0002_personal_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalinfo.Personal')),
            ],
        ),
    ]
