# Generated by Django 2.2.2 on 2019-12-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
