# Generated by Django 2.2.1 on 2019-08-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradigrams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paradigm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradigrams.Paradigram')),
            ],
        ),
    ]
